--- #YAML:1.0
name:                Perl-Critic-Itch
version:             1.0
abstract:            Perl::Critic::Itch - A remedy for some stuff that causes me Itches
license:             perl
author:              
    - Marcelo Rodrigues <marcelo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Perl::Critic:                  1.07
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
