--- #YAML:1.0
name:                Perl-Critic-Itch
version:             0.02
abstract:            Perl::Critic::Itch - A collection of Policies to solve some Itches
license:             perl
author:              
    - Marcelo Rodrigues <marcelo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
